### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 1573712107** [Desamod/BoolBot#14]
Traceback (most recent call last):
  File "D:\TGbot\BoolBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\TGbot\BoolBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "D:\TGbot\BoolBot\bot\utils\launcher.py", line 9, in <module>
    from bot.core.tapper import run_tapper
  File "D:\TGbot\BoolBot\bot\core\tapper.py", line 16, in <module>
    from ..utils.tg_manager.TGSession import TGSession
ModuleNotFoundError: No module named 'bot.utils.tg_manager.TGSession'

**Comment by Desamod** [comment]
Python version?

**Comment by 1573712107** [comment]
PYTHON 3.11.5

**Comment by Desamod** [comment]
Use only 3.10

**Comment by AntiWarforever** [comment]
In last update works on py 3.11 but after new update don't work i thinks this has nothing to do with the version
I have same problem too
